/**
 * Exhaustive copy maps for every domain enum.
 * When a value is added to the domain, this file must be updated or the build fails.
 */

import type {
  ItemStatus,
  IdentificationStatus,
  IdentificationFailureReason,
  StorageType,
  AcquiredVia,
  RawConditionTier,
  AutoType,
  Confidence,
} from '@prisma/client';

// ---------------------------------------------------------------------------
// String unions not generated by Prisma
// ---------------------------------------------------------------------------

type IdentificationFlag =
  | 'no_catalog_match'
  | 'redemption'
  | 'parallel_uncertain'
  | 'serial_unreadable'
  | 'serial_mismatch'
  | 'providers_disagree'
  | 'auto_uncertain'
  | 'photo_quality'
  | 'no_back_photo'
  | 'variation_possible'
  | 'rookie_conflict'
  | 'no_scp_match'
  | 'cardsight_failed'
  | 'catalog_search_failed'
  | 'slab'
  | 'parallel_fetch_failed'
  | 'scp_linkage_failed'
  | 'card_number_mismatch'
  | 'card_number_unverified'
  | 'card_number_ocr_only'
  | 'card_number_unreadable';

type SaleType =
  | 'auction'
  | 'fixed_price'
  | 'best_offer_accepted'
  | 'best_offer_unknown_price'
  | 'unknown';

// ---------------------------------------------------------------------------
// 1. Identification flags
// ---------------------------------------------------------------------------

export const identificationFlagCopy = {
  no_catalog_match: 'Not in the price catalogs yet',
  redemption: 'This is a voucher you mail in \u2014 the actual card comes later',
  parallel_uncertain: 'Not sure which version this is',
  serial_unreadable: "Couldn't read the serial number",
  serial_mismatch: "Serial number doesn't match",
  providers_disagree: 'Two sources disagree \u2014 worth a look',
  auto_uncertain: 'Not sure about the autograph',
  photo_quality: 'Photo quality may affect results',
  no_back_photo: "No back photo \u2014 can't check everything",
  variation_possible: 'This card may have a variant',
  rookie_conflict: 'Rookie status differs from the catalog',
  no_scp_match: 'No price match found',
  cardsight_failed: 'Card lookup service unavailable',
  catalog_search_failed: 'Catalog search failed',
  slab: 'Graded slab detected',
  parallel_fetch_failed: "Couldn't load parallel options",
  scp_linkage_failed: 'Price linkage failed',
  card_number_mismatch: 'Card number needs verification',
  card_number_unverified: 'Card number not confirmed',
  card_number_ocr_only: 'Card number read by backup scanner only',
  card_number_unreadable: "Couldn't read the card number",
} as const satisfies Record<IdentificationFlag, string>;

// ---------------------------------------------------------------------------
// 2. Item status
// ---------------------------------------------------------------------------

export const itemStatusCopy = {
  draft: 'Scanning',
  identifying: 'Identifying...',
  needs_review: 'Needs review',
  owned: 'In collection',
  sold: 'Sold',
  removed: 'Removed',
} as const satisfies Record<ItemStatus, string>;

// ---------------------------------------------------------------------------
// 3. Identification status
// ---------------------------------------------------------------------------

export const identificationStatusCopy = {
  queued: 'Waiting',
  running: 'Identifying...',
  ready: 'Ready to add',
  needs_review: 'Needs review',
  confirmed: 'Confirmed',
  failed: 'Failed',
} as const satisfies Record<IdentificationStatus, string>;

// ---------------------------------------------------------------------------
// 4. Failure reason
// ---------------------------------------------------------------------------

export const failureReasonCopy = {
  quota_exhausted:
    "We've used this month's lookups. Try again next month or enter it yourself.",
  provider_unavailable:
    'The identification service is temporarily unavailable. Try again in a few minutes.',
  image_unreadable:
    "The photo wasn't clear enough to read. Try retaking it with better lighting.",
  internal: 'Something went wrong on our end. Try again.',
} as const satisfies Record<IdentificationFailureReason, string>;

// ---------------------------------------------------------------------------
// 5. Storage type
// ---------------------------------------------------------------------------

export const storageCopy = {
  toploader: 'Toploader',
  penny_sleeve: 'Penny sleeve',
  binder: 'Binder',
  magnetic: 'Magnetic case',
  slab: 'Slab',
  none: 'None',
  unknown: 'Not set',
} as const satisfies Record<StorageType, string>;

// ---------------------------------------------------------------------------
// 6. Acquired via
// ---------------------------------------------------------------------------

export const acquiredViaCopy = {
  purchase: 'Purchased',
  pack_pull: 'Pack pull',
  trade: 'Trade',
  gift: 'Gift',
  unknown: 'Not set',
} as const satisfies Record<AcquiredVia, string>;

// ---------------------------------------------------------------------------
// 7. Raw condition tier
// ---------------------------------------------------------------------------

export const rawConditionTierCopy = {
  market: 'Typical raw card',
  nm_mt: 'Light wear',
  ex_mt: 'Clear wear',
  ex: 'Worn',
  vg: 'Heavy wear',
  poor: 'Damaged',
} as const satisfies Record<RawConditionTier, string>;

// ---------------------------------------------------------------------------
// 8. Auto type
// ---------------------------------------------------------------------------

export const autoTypeCopy = {
  on_card: 'On-card autograph',
  sticker: 'Sticker autograph',
  cut: 'Cut autograph',
  unknown: 'Autograph (type unknown)',
} as const satisfies Record<AutoType, string>;

// ---------------------------------------------------------------------------
// 9. Confidence
// ---------------------------------------------------------------------------

export const confidenceCopy = {
  high: 'Based on recent sales',
  medium: 'Estimated with some uncertainty',
  low: 'Rough estimate',
  none: 'No value yet',
} as const satisfies Record<Confidence, string>;

// ---------------------------------------------------------------------------
// 10. Sale type
// ---------------------------------------------------------------------------

export const saleTypeCopy = {
  auction: 'Auction',
  fixed_price: 'Buy it now',
  best_offer_accepted: 'Best offer',
  best_offer_unknown_price: 'Best offer (price unknown)',
  unknown: 'Sale',
} as const satisfies Record<SaleType, string>;

// ---------------------------------------------------------------------------
// Help panel content
// ---------------------------------------------------------------------------

export interface HelpEntry {
  title: string;
  body: string;
}

type HelpFlag =
  | 'parallel_uncertain'
  | 'no_catalog_match'
  | 'photo_quality'
  | 'no_back_photo'
  | 'variation_possible'
  | 'serial_mismatch'
  | 'rookie_conflict'
  | 'no_scp_match'
  | 'provider_unavailable'
  | 'image_unreadable'
  | 'redemption'
  | 'quota_exhausted';

export const helpPanelContent = {
  parallel_uncertain: {
    title: 'Which version is this?',
    body: "Your card may be a base, refractor, prizm, or other parallel. We couldn't tell from the photos. Pick the correct version so the value is accurate.",
  },
  no_catalog_match: {
    title: 'Not in the catalogs',
    body: "We searched our price sources but didn't find this card. It may be too new, too obscure, or from a set we don't cover yet. You can enter the details yourself.",
  },
  photo_quality: {
    title: 'Photo quality',
    body: 'Glare, blur, or cropping made it harder to read your card. You can retake the photo for better results, or confirm the details manually.',
  },
  no_back_photo: {
    title: 'No back photo',
    body: "Without a back photo we can't verify the card number, set details, or serial number. Add a back photo for a more accurate identification.",
  },
  variation_possible: {
    title: 'Possible variant',
    body: 'This card might be a short print, photo variation, or other variant. Check the photo and card number against known variations for this set.',
  },
  serial_mismatch: {
    title: 'Serial number mismatch',
    body: "The serial number we read doesn't match what we expected for this card. Double-check the number on the card and correct it if needed.",
  },
  rookie_conflict: {
    title: 'Rookie status conflict',
    body: "Our catalog says this card's rookie status is different from what we detected. Verify whether the card has a rookie logo or designation.",
  },
  no_scp_match: {
    title: 'No price match',
    body: "We identified the card but couldn't find a matching price entry. The value shown may be less accurate until a price match is confirmed.",
  },
  provider_unavailable: {
    title: 'Service temporarily down',
    body: 'The identification service is having issues right now. Your card has been saved and will be retried automatically. You can also try again manually.',
  },
  image_unreadable: {
    title: 'Photo not readable',
    body: "We couldn't read enough detail from your photo. Try retaking with even lighting, no glare, and the full card in frame.",
  },
  redemption: {
    title: 'Redemption card',
    body: "This looks like a redemption voucher, not the actual card. You mail it in to receive the real card. We can't value it until you know which card you'll receive.",
  },
  quota_exhausted: {
    title: 'Monthly lookups used',
    body: "You've used all your identification lookups for this billing period. You can still add cards by entering the details manually, or wait until next month.",
  },
} as const satisfies Record<HelpFlag, HelpEntry>;
